/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

/**
 *
 * @author Brayan Puzul
 */
public class teorem6 extends javax.swing.JFrame {

    /**
     * Creates new form teorem6
     */
    public teorem6() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        n01 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        n02 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        n04 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        n1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        n2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        n3 = new javax.swing.JLabel();
        n4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        res2 = new javax.swing.JLabel();
        res1 = new javax.swing.JLabel();
        n03 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        e2 = new javax.swing.JLabel();
        e = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        i = new javax.swing.JLabel();
        o2 = new javax.swing.JLabel();
        e1 = new javax.swing.JLabel();
        o = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        e3 = new javax.swing.JLabel();
        s = new javax.swing.JButton();
        e7 = new javax.swing.JLabel();
        e4 = new javax.swing.JLabel();
        e6 = new javax.swing.JLabel();
        i2 = new javax.swing.JLabel();
        e5 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("TEOREMA 6");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 140, 40));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("El numero de conbinaciones de n objetos distintos tomados de r ala vez es :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 790, 30));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 51));
        jLabel7.setText("Un niño le pide a su madre que le lleve cinco cartuchos de Game-boyTM de su ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 830, 30));

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 51));
        jLabel10.setText("juegos recreativos y ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 220, 30));

        n01.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        n01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(n01, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 40, 30));

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 51));
        jLabel8.setText("coleccion de ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 140, 30));

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 255, 51));
        jLabel11.setText("podria su madre llevarle ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 260, -1));

        n02.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        n02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(n02, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 40, 30));

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 255, 51));
        jLabel12.setText("juegos recreativos y");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 220, -1));

        n04.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        n04.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(n04, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 40, 30));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 51));
        jLabel9.setText("de deportes?");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 160, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("resultado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 140, 40));

        n1.setBackground(new java.awt.Color(255, 255, 255));
        n1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        n1.setForeground(new java.awt.Color(153, 0, 204));
        n1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 30, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("(");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 20, 80));

        n2.setBackground(new java.awt.Color(255, 255, 255));
        n2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        n2.setForeground(new java.awt.Color(153, 0, 204));
        n2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(n2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 30, 30));

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 60)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText(")");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 20, 80));

        n3.setBackground(new java.awt.Color(255, 255, 255));
        n3.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        n3.setForeground(new java.awt.Color(0, 255, 255));
        n3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(n3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 30, 30));

        n4.setBackground(new java.awt.Color(255, 255, 255));
        n4.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        n4.setForeground(new java.awt.Color(0, 255, 255));
        n4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(n4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 30, 30));

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 60)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("(");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 20, 80));

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 60)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText(")");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 20, 80));

        res2.setBackground(new java.awt.Color(255, 255, 51));
        res2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        res2.setForeground(new java.awt.Color(0, 0, 0));
        res2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        res2.setOpaque(true);
        getContentPane().add(res2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 380, 60));

        res1.setBackground(new java.awt.Color(255, 255, 51));
        res1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        res1.setForeground(new java.awt.Color(0, 0, 0));
        res1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        res1.setOpaque(true);
        getContentPane().add(res1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 380, 60));

        n03.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        n03.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(n03, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 40, 30));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 51));
        jLabel5.setText("de deportes ¿De cuantas maneras");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 390, 30));

        jLabel1.setBackground(new java.awt.Color(102, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 140, 10));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText(")");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 20, 50));

        a.setBackground(new java.awt.Color(255, 255, 255));
        a.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        a.setForeground(new java.awt.Color(153, 0, 204));
        a.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 40, 30));

        e2.setBackground(new java.awt.Color(255, 255, 255));
        e2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        e2.setForeground(new java.awt.Color(153, 0, 204));
        e2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 30, 30));

        e.setBackground(new java.awt.Color(255, 255, 255));
        e.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        e.setForeground(new java.awt.Color(153, 0, 204));
        e.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 40, 30));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("-");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 30, 20));

        a2.setBackground(new java.awt.Color(255, 255, 255));
        a2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        a2.setForeground(new java.awt.Color(153, 0, 204));
        a2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 30, 30));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("(");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 20, 50));

        jLabel22.setBackground(new java.awt.Color(102, 0, 0));
        jLabel22.setOpaque(true);
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 140, 10));

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText(")");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 20, 50));

        i.setBackground(new java.awt.Color(255, 255, 255));
        i.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        i.setForeground(new java.awt.Color(0, 255, 255));
        i.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(i, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 40, 30));

        o2.setBackground(new java.awt.Color(255, 255, 255));
        o2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        o2.setForeground(new java.awt.Color(0, 255, 255));
        o2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(o2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 30, 30));

        e1.setBackground(new java.awt.Color(255, 255, 255));
        e1.setFont(new java.awt.Font("Goudy Stout", 3, 14)); // NOI18N
        e1.setForeground(new java.awt.Color(255, 255, 51));
        e1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e1.setText("!");
        getContentPane().add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 20, 40));

        o.setBackground(new java.awt.Color(255, 255, 255));
        o.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        o.setForeground(new java.awt.Color(0, 255, 255));
        o.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(o, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 40, 30));

        jLabel27.setBackground(new java.awt.Color(0, 0, 0));
        jLabel27.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setText("-");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 30, 20));

        e3.setBackground(new java.awt.Color(255, 255, 255));
        e3.setFont(new java.awt.Font("Goudy Stout", 3, 14)); // NOI18N
        e3.setForeground(new java.awt.Color(255, 255, 51));
        e3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e3.setText("!");
        getContentPane().add(e3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 30, 40));

        s.setBackground(new java.awt.Color(0, 0, 0));
        s.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        s.setForeground(new java.awt.Color(255, 0, 0));
        s.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/13.gif"))); // NOI18N
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });
        getContentPane().add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 480, 70, 70));

        e7.setBackground(new java.awt.Color(255, 255, 255));
        e7.setFont(new java.awt.Font("Goudy Stout", 3, 14)); // NOI18N
        e7.setForeground(new java.awt.Color(255, 255, 51));
        e7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e7.setText("!");
        getContentPane().add(e7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 20, 40));

        e4.setBackground(new java.awt.Color(255, 255, 255));
        e4.setFont(new java.awt.Font("Goudy Stout", 3, 14)); // NOI18N
        e4.setForeground(new java.awt.Color(255, 255, 51));
        e4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e4.setText("!");
        getContentPane().add(e4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 20, 40));

        e6.setBackground(new java.awt.Color(255, 255, 255));
        e6.setFont(new java.awt.Font("Goudy Stout", 3, 14)); // NOI18N
        e6.setForeground(new java.awt.Color(255, 255, 51));
        e6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e6.setText("!");
        getContentPane().add(e6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 20, 40));

        i2.setBackground(new java.awt.Color(255, 255, 255));
        i2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        i2.setForeground(new java.awt.Color(0, 255, 255));
        i2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(i2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 30, 30));

        e5.setBackground(new java.awt.Color(255, 255, 255));
        e5.setFont(new java.awt.Font("Goudy Stout", 3, 14)); // NOI18N
        e5.setForeground(new java.awt.Color(255, 255, 51));
        e5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e5.setText("!");
        getContentPane().add(e5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 20, 40));

        jLabel29.setBackground(new java.awt.Color(0, 0, 0));
        jLabel29.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 204, 204));
        jLabel29.setText("(");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 20, 50));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/DeliciousSelfassuredArcherfish-size_restricted.gif"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 970, 560));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try {
            int factorial=1;
           int factorial2=1;
           int factorial3=1;
           int factorial4=1;
           int fac=1;
           int fac2=1;
            Integer numero =new Integer (this.n01.getText());
            Integer numero2 =new Integer (this.n02.getText());
            Integer numero3 =new Integer (this.n03.getText());
            Integer numero4 =new Integer (this.n04.getText());

            for (int i = numero; i >= 1; i--) {
                factorial=factorial * i;
            }
            
            for (int i = numero-numero2; i >= 1; i--) {
                fac=fac * i;
            }
           
            for(int i = numero2; i>=1;i--){
                factorial2=factorial2*i;
            }
            //segundo operacion
            for(int i = numero3; i>=1;i--){
                factorial3=factorial3*i;
            }
            for(int i = numero4; i>=1;i--){
                factorial4=factorial4*i;
            }
            for(int i = numero3-numero4; i>=1;i--){
                fac2=fac2*i;
            }
            
            n1.setText(""+numero);
            n2.setText(""+numero2);
            n3.setText(""+numero3);
            n4.setText(""+numero4);
            a.setText(""+numero);
            a2.setText(""+numero);
            e.setText(""+numero2);
            e2.setText(""+numero2);
            i.setText(""+numero3);
            i2.setText(""+numero3);
            o.setText(""+numero4);
            o2.setText(""+numero4);
            res1.setText(""+factorial/(factorial2*fac));
            res2.setText(""+factorial3/(factorial4*fac2));
        } catch (NumberFormatException e) {
            res1.setText("Solo se puede ingresar numeros");
            res2.setText("Solo se puede ingresar numeros");
        } 

    }//GEN-LAST:event_jButton1ActionPerformed

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
        inicio teo2=new inicio();
        teo2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teorem6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teorem6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teorem6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teorem6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teorem6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel e;
    private javax.swing.JLabel e1;
    private javax.swing.JLabel e2;
    private javax.swing.JLabel e3;
    private javax.swing.JLabel e4;
    private javax.swing.JLabel e5;
    private javax.swing.JLabel e6;
    private javax.swing.JLabel e7;
    private javax.swing.JLabel i;
    private javax.swing.JLabel i2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField n01;
    private javax.swing.JTextField n02;
    private javax.swing.JTextField n03;
    private javax.swing.JTextField n04;
    private javax.swing.JLabel n1;
    private javax.swing.JLabel n2;
    private javax.swing.JLabel n3;
    private javax.swing.JLabel n4;
    private javax.swing.JLabel o;
    private javax.swing.JLabel o2;
    private javax.swing.JLabel res1;
    private javax.swing.JLabel res2;
    private javax.swing.JButton s;
    // End of variables declaration//GEN-END:variables
}
